database:
  driver: postgres
  host: localhost
  port: 5432
  name: pastebin
  user: root
  password: admin
  sslmode: disable
#  source: postgresql://LOGIN:PASSWORD@host:port/name?sslmode=sslmode
grpc:
  port: 5143
  timeout: 10h
token_ttl: 1h

